config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  namespace :admin do
    resources :orders
    resources :order_items
    resources :order_statuses
    resources :products
    resources :product_categories
    root to: "orders#index"
  end

  resources :charges
  resources :products, only: [:index, :show]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]

  get '/category/:id',  to: 'product_categories#show', as: "category"
  root to: "products#index"

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items.includes(product: [image_attachment: :blob])
  end
end

app/views/carts/_cart_row.html.erb
<div class="row">
  <div class="col-md-4">
    <%= image_tag(product.image.variant(resize_to_fill: [192, 192]), class: "img-fluid") if product.image.attached? %>
  </div>
  <div class="col">
    <div class="card-body">
      <%= form_for order_item, remote: true do |f| %>
        <div class="form-group">
          <%= f.number_field :quantity, value: order_item.quantity.to_i, class: "form-control", min: 1 %>
          <%= f.hidden_field :product_id, value: product.id %>
        </div>
        <div class="btn-group">
          <%= f.submit "Update Quantity", class: "btn btn-primary" %>
          <%= link_to "Delete", order_item, {data: {confirm: "Are you sure you wish to delete the product '#{order_item.product.name}' from your cart?"}, method: :delete, remote: true, class: "btn btn-danger"} %>
        </div>
        <p>
          Unit Price: <%= number_to_currency order_item.unit_price %>
        </p>
        <p>Total Price:
          <%= number_to_currency order_item.total_price %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/carts/_shopping_cart.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% @order_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<% if @order_items.size == 0 %>
  <p class="text-center">
    There are no items in your shopping cart. Please <%= link_to "go back",
                                                                 root_path %> and add some items to your cart.
  </p>
<% else %>
  <div class="container">
    <div class="row">
      <div class="col-md-8 offset-md-2">
        <div class="card">
          <% @order_items.each do |order_item| %>
            <%= render 'carts/cart_row', product: order_item.product, order_item: order_item, show_total: true %>
          <% end %>
          <%= link_to "Pay", new_charge_path, class: "btn btn-info", data: { turbolinks: 'false'} %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/carts/show.html.erb
<div class="shopping-cart"><%= render "shopping_cart" %></div>