config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  namespace :admin do
    resources :orders
    resources :order_items
    resources :order_statuses
    resources :products
    resources :product_categories
    root to: "orders#index"
  end

  resources :charges
  resources :products, only: [:index, :show]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]

  get '/category/:id',  to: 'product_categories#show', as: "category"
  root to: "products#index"

end

app/views/layouts/_alert.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/layouts/_auth.html.erb
<% if user_signed_in? %>
  <ul class="navbar-nav">
    <li class="nav-item dropdown">
      <%= link_to current_user.email, "#", class: "nav-link dropdown-toggle", role: "button", "data-bs-toggle": "dropdown" %>
      <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'dropdown-item' %>
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'dropdown-item' %>
      </div>
    </li>
  </ul>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, class: "btn btn-outline-primary mx-1", role: "button" %>
  <%= link_to "Login", new_user_session_path, class: "btn btn-primary", role: "button" %>
<% end %>

app/views/layouts/_cart_text.html.erb
<div class="cart-text">
  <%= link_to "#{current_order.order_items.size} Items in Cart ( #{number_to_currency current_order.subtotal} )", cart_path, class: "btn btn-outline-dark" %>
</div>

app/views/layouts/_footer.html.erb
<footer class="pt-4 my-md-5 pt-md-5 border-top">
  <div class="row">
    <div class="col-12 col-md">
      <small class="d-block mb-3 text-muted">Jon Snow &copy; 2019</small>
    </div>
    <div class="col-6 col-md">
      <h5>Features</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Cool stuff</a></li>
        <li><a class="text-muted" href="#">Random feature</a></li>
        <li><a class="text-muted" href="#">Team feature</a></li>
        <li><a class="text-muted" href="#">Stuff for developers</a></li>
        <li><a class="text-muted" href="#">Another one</a></li>
        <li><a class="text-muted" href="#">Last time</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>Resources</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Resource</a></li>
        <li><a class="text-muted" href="#">Resource name</a></li>
        <li><a class="text-muted" href="#">Another resource</a></li>
        <li><a class="text-muted" href="#">Final resource</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>About</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Team</a></li>
        <li><a class="text-muted" href="#">Locations</a></li>
        <li><a class="text-muted" href="#">Privacy</a></li>
        <li><a class="text-muted" href="#">Terms</a></li>
      </ul>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-light fixed-top bg-light">
  <div class="container-fluid">
    <%= link_to "Waroong", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
          <a class="nav-link" href="#">Today's Deals</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% @categories.each do |cat| %>
              <%= link_to cat.name.capitalize, category_path(cat), class: "dropdown-item" %>
            <% end %>
          </ul>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="#">Gift Cards</a>
        </li>
        <form class="form-inline">
          <input aria-label="Search" class="form-control mr-sm-2" placeholder="Search" type="search">
        </form>
      </ul>
      <form class="d-flex">
        <%= render 'layouts/cart_text' %>
        <%= render 'layouts/auth' %>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/_slider.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag "slide2.jpg", class:"img-fluid" %>
      <!--
        <div class="container">
          <div class="carousel-caption text-left">
            <h1>Example headline.</h1>
            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
            <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
          </div>
        </div>
      -->
    </div>
    <div class="carousel-item">
      <%= image_tag "slide3.jpg", class:"img-fluid" %>
    </div>
    <div class="carousel-item">
      <%= image_tag "slide4.jpg", class:"img-fluid" %>
    </div>
  </div>
  <a
    class="carousel-control-prev"
    href="#myCarousel"
    role="button"
    data-slide="prev"
  >
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a
    class="carousel-control-next"
    href="#myCarousel"
    role="button"
    data-slide="next"
  >
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Waroong</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= render "layouts/alert" %>
    <div class="container">
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>